{{ if .Values.rbac.install }}
# {{- $serviceName := include "demo-gradle.fullname" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "demo-gradle.fullname" . }}
{{- if .Values.rbac.serviceAccountAnnotations }}
  annotations:
{{ toYaml .Values.rbac.serviceAccountAnnotations | indent 4 }}
{{ end }}
  labels:
{{ include "demo-gradle.labels.standard" . | indent 4 }}
    # app: {{ $serviceName }}
    # chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    # release: "{{ .Release.Name }}"
    # heritage: "{{ .Release.Service }}"
{{ end }}