{{ if .Values.rbac.create }}
# {{- $serviceName := include "demo-gradle.fullname" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "demo-gradle.serviceAccountName" . }}
  labels:
{{ include "demo-gradle.labels.standard" . | indent 4 }}
    # app: {{ $serviceName }}
    # chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    # release: "{{ .Release.Name }}"
    # heritage: "{{ .Release.Service }}"
{{ end }}