name: demo-gradle
version: 0.0.1
appVersion: 0.0.1
description: A Helm chart for Kubernetes - Demo Project for Gradle/Spring Cloud
sources:
- https://gitea.ssii.com/RDP/demo-gradle.git
maintainers:
- name: huangch
  email: huangch@rdp.dev